nodeLinker: node-modules

npmPublishAccess: public

npmRegistries:
  "https://registry.npmjs.org":
    npmAuthToken: $NPM_PUBLISH_TOKEN

npmScopes:
  your-scope:
    npmAuthToken: $NPM_READ_TOKEN
    npmRegistryServer: "https://registry.npmjs.org"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
