// String Manipulation Functions
export * from "./capitalize";
export * from "./kebabCase";
export * from "./slugify";
export * from "./truncate";
export * from "./dashToCamelCase";
export * from "./toCamelCase";
export * from "./endsWith";
export * from "./pluralize";
export * from "./matchAll";
export * from "./removeSymbolAt";
export * from "./removeNewLinesFromJson";
export * from "./removeNewLinesFromString";
export * from "./removeSpacesFromJson";
export * from "./removeSpacesFromString"; 