name: Yarn Install and Test

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'

      - name: Load .env file if exists
        run: |
          if [ -f .env ]; then
            set -a
            source .env
            set +a
          fi

      - name: Set Environment Variables with fallback to .env
        run: |
          echo "NPM_READ_TOKEN=${{ secrets.NPM_READ_TOKEN || env.NPM_READ_TOKEN }}" >> $GITHUB_ENV
          echo "NPM_PUBLISH_TOKEN=${{ secrets.NPM_PUBLISH_TOKEN || env.NPM_PUBLISH_TOKEN }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test
